# Restores RDS snapshots
service: data-checker 

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-2
  stage: production
  environment:
    DB_SG: ""
  iamRoleStatements:
  #  - Effect: "Allow"
  #    Action: "rds:RestoreDBInstanceToPointInTime"
  #    Resource: "*" 
  #  - Effect: "Allow"
  #    Action: 
  #      - kms:DescribeKey
  #      - kms:CreateGrant
  #    Resource: "*"    

functions:
  main:
    handler: handler.do

package:
  exclude:
    - node_modules/**
    - venv/**
    - package-lock.json
    - package.json


plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true