# Restores RDS snapshots
service: rcvrability 

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-2
  stage: production


functions:
  main:
    handler: handler.do
    events:
      - schedule: cron(0 22 * * ? *)

# package:
#   exclude:
#     - node_modules/**
#     - venv/**
#     - package-lock.json
#     - package.json


# plugins:
#   - serverless-python-requirements
# custom:
#   pythonRequirements:
#     dockerizePip: true