# Restores RDS snapshots
service: restore-rds-snapshots 

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-2
  stage: production
  environment:
    DB_NAME: ""
    DB_SECURITY_GROUP_ID: ""
    DB_SUBNET_GROUP_NAME: ""
  iamRoleStatements:
   - Effect: "Allow"
     Action: "rds:RestoreDBInstanceToPointInTime"
     Resource: "*" 
   - Effect: "Allow"
     Action: 
       - kms:DescribeKey
       - kms:CreateGrant
     Resource: "*"    

functions:
  main:
    handler: handler.do
    events:
      - schedule: cron(0 22 * * ? *)
        enabled: false

package:
  exclude:
    - node_modules/**
    - venv/**
    - package-lock.json
    - package.json


plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true