# Restores RDS snapshots
service: restore-rds-snapshots 

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    DB_NAME: ${opt:db_name}
    DB_SECURITY_GROUP_ID: ${opt:db_security_group_id}
    LAMBDA_SECURITY_GROUP_ID: ${opt:lambda_security_group_id}
    DB_SUBNET_GROUP_NAME: ${opt:subnet_group_name}
    STAGE: ${opt:stage}
  iamRoleStatements:
   - Effect: "Allow"
     Action: 
       - rds:RestoreDBInstanceToPointInTime
       - rds:CreateEventSubscription
       - rds:DescribeEventSubscriptions
       - rds:DeleteEventSubscription
     Resource: "*" 
   - Effect: "Allow"
     Action: 
       - kms:DescribeKey
       - kms:CreateGrant
     Resource: "*"    

functions:
  main:
    handler: handler.restore
    events:
      - schedule: cron(0 22 * * ? *)
        enabled: false

package:
  exclude:
    - node_modules/**
    - venv/**
    - package-lock.json
    - package.json

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true